---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-to-avahi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-ingress-to-avahi
  namespace: ingress-to-avahi
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: k8s-ingress-to-avahi
  timeout: 60s
  url: ssh://git@github.com/piotrb/k8s-ingress-to-avahi.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-to-avahi
  namespace: ingress-to-avahi
spec:
  interval: 30m
  chart:
    spec:
      chart: . 
      sourceRef:
        kind: GitRepository
        name: ingress-to-avahi
        namespace: ingress-to-avahi
      interval: 1h
  values: {}
